import "./globals.css";
import { Inter, Source_Sans_3 } from "next/font/google";

const sourceSansPro = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "Slciing Frontend Test | Vicky Herdiansyah Adri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sourceSansPro.className}>{children}</body>
    </html>
  );
}
